plugins:
  - jekyll-paginate


include: ["_pages","_category","images"]

permalink: /:title/

# Paginate
paginate: 15
paginate_path: /page/:num

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Exclude
exclude: [
    'README.md'
]
